In [2]:
import json
import pandas as pd
import numpy as np


def parse_congresses(df):
    # Parse the 'congresses' column
    df['congresses'] = df['congresses'].apply(json.loads)

    # Flatten the nested structure
    rows = []
    for _, row in df.iterrows():
        for congress in row['congresses']:
            new_row = row.drop('congresses').to_dict()
            new_row.update(congress)
            rows.append(new_row)

    return pd.DataFrame(rows)

In [3]:
democrats_df = pd.read_csv("../DATA/democrats.csv")
other_df = pd.read_csv("../DATA/else.csv")

democrats_parsed_df = parse_congresses(democrats_df)
other_parsed_df = parse_congresses(other_df)

In [4]:
democrats_parsed_df

,id,givenName,familyName,middleName,unaccentedGivenName,unaccentedFamilyName,unaccentedMiddleName,nickName,honorificPrefix,honorificSuffix,honorificTitle,birthYear,deathYear,position,congressNumber,stateName,parties,electionCirca,electionDate,leadershipPositions
0,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,NaN,1938,NaN,Representative,99,HI,[Democrat],NaN,NaN,NaN
1,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,NaN,1938,NaN,Representative,102,HI,[Democrat],NaN,NaN,NaN
2,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,NaN,1938,NaN,Representative,103,HI,[Democrat],NaN,NaN,NaN
3,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,NaN,1938,NaN,Representative,104,HI,[Democrat],NaN,NaN,NaN
4,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,NaN,1938,NaN,Representative,105,HI,[Democrat],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7726,Z000001,Clement,Zablocki,John,Clement,Zablocki,John,NaN,NaN,NaN,NaN,1912,1983.0,Representative,97,WI,[Democrat],NaN,NaN,NaN
7727,Z000002,Leo,Zeferetti,C.,Leo,Zeferetti,C.,NaN,NaN,NaN,NaN,1927,2018.0,Representative,94,NY,[Democrat],NaN,NaN,NaN
7728,Z000002,Leo,Zeferetti,C.,Leo,Zeferetti,C.,NaN,NaN,NaN,NaN,1927,2018.0,Representative,95,NY,[Democrat],NaN,NaN,NaN
7729,Z000002,Leo,Zeferetti,C.,Leo,Zeferetti,C.,NaN,NaN,NaN,NaN,1927,2018.0,Representative,96,NY,[Democrat],NaN,NaN,NaN
7730,Z000002,Leo,Zeferetti,C.,Leo,Zeferetti,C.,NaN,NaN,NaN,NaN,1927,2018.0,Representative,97,NY,[Democrat],NaN,NaN,NaN

In [5]:
combined_df = pd.concat([democrats_parsed_df, other_parsed_df], ignore_index=True)
combined_df

,id,givenName,familyName,middleName,unaccentedGivenName,unaccentedFamilyName,unaccentedMiddleName,nickName,honorificPrefix,honorificSuffix,honorificTitle,birthYear,deathYear,position,congressNumber,stateName,parties,electionCirca,electionDate,leadershipPositions
0,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,NaN,1938,NaN,Representative,99,HI,[Democrat],NaN,NaN,NaN
1,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,NaN,1938,NaN,Representative,102,HI,[Democrat],NaN,NaN,NaN
2,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,NaN,1938,NaN,Representative,103,HI,[Democrat],NaN,NaN,NaN
3,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,NaN,1938,NaN,Representative,104,HI,[Democrat],NaN,NaN,NaN
4,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,NaN,1938,NaN,Representative,105,HI,[Democrat],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13787,Z000018,Ryan,Zinke,NaN,Ryan,Zinke,NaN,NaN,NaN,NaN,NaN,1961,NaN,Representative,114,MT,[Republican],NaN,NaN,NaN
13788,Z000018,Ryan,Zinke,NaN,Ryan,Zinke,NaN,NaN,NaN,NaN,NaN,1961,NaN,Representative,115,MT,[Republican],False,NaN,NaN
13789,Z000018,Ryan,Zinke,NaN,Ryan,Zinke,NaN,NaN,NaN,NaN,NaN,1961,NaN,Representative,118,MT,[Republican],False,NaN,NaN
13790,Z000014,Edwin,Zschau,Van Wyck,Edwin,Zschau,Van Wyck,NaN,NaN,NaN,NaN,1940,NaN,Representative,98,CA,[Republican],NaN,NaN,NaN
13791,Z000014,Edwin,Zschau,Van Wyck,Edwin,Zschau,Van Wyck,NaN,NaN,NaN,NaN,1940,NaN,Representative,99,CA,[Republican],NaN,NaN,NaN

In [7]:
combined_df['electionYear'] = (combined_df['congressNumber'] -1 ) * 2 + 1788
combined_df['ageDuringElection'] = combined_df['electionYear'] - combined_df['birthYear']
combined_df

,id,givenName,familyName,middleName,unaccentedGivenName,unaccentedFamilyName,unaccentedMiddleName,nickName,honorificPrefix,honorificSuffix,...,deathYear,position,congressNumber,stateName,parties,electionCirca,electionDate,leadershipPositions,electionYear,ageDuringElection
0,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,...,NaN,Representative,99,HI,[Democrat],NaN,NaN,NaN,1984,46
1,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,...,NaN,Representative,102,HI,[Democrat],NaN,NaN,NaN,1990,52
2,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,...,NaN,Representative,103,HI,[Democrat],NaN,NaN,NaN,1992,54
3,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,...,NaN,Representative,104,HI,[Democrat],NaN,NaN,NaN,1994,56
4,A000014,Neil,Abercrombie,NaN,Neil,Abercrombie,NaN,NaN,NaN,NaN,...,NaN,Representative,105,HI,[Democrat],NaN,NaN,NaN,1996,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13787,Z000018,Ryan,Zinke,NaN,Ryan,Zinke,NaN,NaN,NaN,NaN,...,NaN,Representative,114,MT,[Republican],NaN,NaN,NaN,2014,53
13788,Z000018,Ryan,Zinke,NaN,Ryan,Zinke,NaN,NaN,NaN,NaN,...,NaN,Representative,115,MT,[Republican],False,NaN,NaN,2016,55
13789,Z000018,Ryan,Zinke,NaN,Ryan,Zinke,NaN,NaN,NaN,NaN,...,NaN,Representative,118,MT,[Republican],False,NaN,NaN,2022,61
13790,Z000014,Edwin,Zschau,Van Wyck,Edwin,Zschau,Van Wyck,NaN,NaN,NaN,...,NaN,Representative,98,CA,[Republican],NaN,NaN,NaN,1982,42
13791,Z000014,Edwin,Zschau,Van Wyck,Edwin,Zschau,Van Wyck,NaN,NaN,NaN,...,NaN,Representative,99,CA,[Republican],NaN,NaN,NaN,1984,44

In [9]:
combined_df.to_csv("../DATA/house_biographic.csv")